name: 'my_databricks_project'
version: '1.0.0'
config-version: 2

profile: 'my_databricks_project'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  my_databricks_project:
    # 1. Bronze folder ke saare models source_db mein jayein
    bronze:
      +schema: source_db
      +materialized: table

    # 2. Silver folder ke saare models EXACT silver_db mein jayein
    silver:
      +schema: silver_db
      +materialized: table

    # 3. Gold folder ke saare models EXACT gold_db mein jayein
    gold:
      +schema: gold_db
      +materialized: table